### ISSUE TITLE
[FG3] Multi project workspace no longer works after updating from ForgeGradle 2

### ISSUE THREAD

**Issue by darkevilmac** [MinecraftForge/ForgeGradle#557]
After starting to upgrade my projects to 1.13, and managing to get some of them to compile I've run into an issue when trying to run the game. Whenever I try to launch the game it ends up throwing exceptions and preventing me from testing my project.

This happens whether I use the runClient task from gradle directly, or if I use the run config generated for IntelliJ.

Log with errors: https://gist.github.com/59345bf2e78fe95f87f2d45c19468065
Older project using a similar structure: https://github.com/elytra/DavincisVessels
Current 1.13 project that the issue occurs on: http://github.com/TridentMC/Molecule

**Comment by tterrag1098** [comment]
Fixed via https://github.com/MinecraftForge/ForgeGradle/pull/546

**Comment by darkevilmac** [comment]
Just tested with the newest forge and I'm getting the same errors. Same thing with the runClient task and generated IntelliJ config. Is there some additional tweaking I'm going to need to do? I've pushed my update to the new system to my repos.

**Comment by tterrag1098** [comment]
Yes you will absolutely need to update your run configs. Check the new MDK example.

**Comment by darkevilmac** [comment]
I did update my run configs to match the ones in the MDK, I'm still having issues.
