### ISSUE TITLE
[FG2.3] Cannot find hunk target

### ISSUE THREAD

**Issue by AfterRebelion** [MinecraftForge/ForgeGradle#597]
### Info
`./gradlew setupDecompWorkspace --no-daemon` fails on recent 1.12.2 Forge, both with mappings snapshot_20171003 (default one) and stable_39.
Tried with wiped Gradle cache, and it still happens.
This didn't happen with the same settings a couple of months back.
`./gradlew setupDevWorkspace --no-daemon` works fine, and it is what I'm using for the time being.

Was not sure where to report this error, if here on ForgeGradle or the MCPBot issuetrack, but since #365 is here, I think it should be fine.

### Versions
Minecraft version: 1.12.2
ForgeGradle: 2.3-snapshot
Forge: 14.23.5.2838
Java: AdoptOpenJDK HotSpot build 1.8.0_212-b04

### Steps to reproduce
1. Download and extract MDK
2. Run `./gradlew setupDecompWorkspace --no-daemon` on PowerShell
3. The build will fail

### Log
```
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/2.14/userguide/gradle_daemon.html.
This mapping 'snapshot_20171003' was designed for MC 1.12! Use at your own peril.
#################################################
         ForgeGradle 2.3-SNAPSHOT-7764e3e
  https://github.com/MinecraftForge/ForgeGradle
#################################################
                 Powered by MCP
             http://modcoderpack.com
     by: Searge, ProfMobius, R4wk, ZeuX
     Fesh0r, IngisKahn, bspkrs, LexManos
#################################################
:deobfCompileDummyTask
:deobfProvidedDummyTask
:getVersionJson
:extractUserdev
:extractDependencyATs SKIPPED
:extractMcpData SKIPPED
:extractMcpMappings SKIPPED
:genSrgs SKIPPED
:downloadClient SKIPPED
:downloadServer SKIPPED
:splitServerJar SKIPPED
:mergeJars SKIPPED
:deobfMcSRG SKIPPED
:decompileMc SKIPPED
:fixMcSources SKIPPED
:applySourcePatches
Patching failed: net/minecraft/crash/CrashReportCategory.java Cannot find hunk target
  1: Cannot find hunk target @ 0
  1/2 failed
:applySourcePatches FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':applySourcePatches'.
> com.cloudbees.diff.PatchException: Cannot find hunk target

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 36.817 secs
```

**Comment by bs2609** [comment]
For reference: the patch failing to apply is due to extra `(Object)` casts being inserted into calls to `System.arraycopy`, but the reason for these extra casts being generated is unknown.

**Comment by jellysquid3** [comment]
The real issue at hand here continues to evade me. I was recently bitten by the same issue described here (after not having any problems for months), which was only resolved by switching away from Gradle composite builds. I'm not sure why or how this affected the `applySourcePatches` task and allowed things to succeed once again.

The Aether II project can reliably reproduce this issue on my machine and an isolated virtual machine when Gradle Composite Builds are used. Reproduction steps are simple. Clone the repository [from our Gitea](https://gitea.gildedgames.com/GildedGames/The-Aether-II/src/commit/8cb78e4bfc5f3e4aab3fce0af40994496f75d9ec), check out commit `8cb78e4b` (the last commit before we reverted composite builds), and clone all submodules. Running `./gradlew setupDecompWorkspace` will fail with the error detailed above. The issue no longer occurs if you checkout the revision just after this one which reverts composite builds, being revision `8e18148f`.

**Comment by jellysquid3** [comment]
After some further testing, it appears the issue is not as complex as it may seem. As @bs2609 pointed out on Discord, the implementation for AdoptOpenJDK's `System.arraycopy` method has a bit of trickery going on [here](https://github.com/eclipse/openj9/blob/ffeaf288e8334da24f19de88911dab6f3b637042/jcl/src/java.base/share/classes/java/lang/System.java#L352). I suspect that because of this change, the decompiler feels a need to insert casts, which causes the patches to fail.

In my case, switching to my distribution's OpenJDK build fixes the issue. I suspect that switching to an Oracle build of the JDK on Windows would resolve the issue as well.

**Comment by AfterRebelion** [comment]
What you linked is OpenJ9, and as stated, I use the HotSpot version of AdoptOpenJDK.

**Comment by jellysquid3** [comment]
I'm only able to reproduce this specific issue with OpenJ9, and the source code fragment linked above seems to suggest why. Using the HotSpot or plain upstream OpenJDK builds works without issue (and the method in question here for those builds is not any different from Oracle's builds.)

The only explanation that would make sense to me is that your configuration results in using an OpenJ9 build for some reason. It would be worthwhile to see if there's any other versions of Java installed on your system, or if your `JAVA_HOME` environment variable is set to use a different build. As I mention with composite builds, it seems easy to accidentally end up using OpenJ9 for the de-compilation process.

If you're certain a HotSpot build is being used, then I have absolutely no idea what the true issue is.

**Comment by AfterRebelion** [comment]
![imagen](https://user-images.githubusercontent.com/559819/59164724-7418d480-8b11-11e9-9188-0f14e7a84b5a.png)
I'm pretty sure I'm using the HotSpot one. So unless Gradle is doing something funky, this should work fine.
I _do_ have OpenJ9 also installed, but when I did, I uncheked all file and path association options.

Is there any way to see what Gradle is using?

**Comment by JDLogic** [comment]
@AfterRebelion Gradle does not always respect your system's JAVA_HOME property. You can add this line to your `build.gradle` file to check which jvm it's using.
```groovy
println String.join(" ", System.getProperty("java.version"), System.getProperty("java.vm.version"))
```

The issue with OpenJ9 was cause by a bug in ForgeFlower which is now fixed. With that said, FG 2.3 will not support the use of OpenJ9. See Lex's comment [here](https://github.com/MinecraftForge/ForgeGradle/issues/601#issuecomment-505102373).

**Comment by AfterRebelion** [comment]
Thanks to that line, I confirmed it is using Hotspot (It also prompted the windows firewall dialog, that confirmed again it was hotspot)

And on the comment part... Lex was talking about Java 9, not OpenJ9. They are two separate things. And as I said, it doesn't even apply here because I'm using hotspot.

**Comment by JDLogic** [comment]
Theres should be a `decompileMc.log` file located in the gradle build folder (`build/taskLogs/decompileMc.log` maybe). Can you please upload that to pastebin (or something similar) and post a link to it. I have a feeling the decompile task is using the OpenJ9 version for some reason as I just tested with the hotspot build and it works fine.

**Comment by AfterRebelion** [comment]
`build` subfolder isn't even created, since the task exits so early.

Update: Just to make COMPLETELY sure it doesn't use the OpenJ9 for whatever reason, I uninstalled all the Java SDKs I have, except this one:
![imagen](https://user-images.githubusercontent.com/559819/60055352-a283db80-96dd-11e9-8de9-b59590b7671a.png)

And the problem still persists.

**Comment by JDLogic** [comment]
The only other advise I can give it to try running `gradlew clean` and then setup again. That or try starting a completely fresh project in a new directory.

**Comment by LexManos** [comment]
You can try nuking your cache. However, as it sits FG2.3 is old, it also doesn't have the ability for us to update FF or our patches individually like FG3 does. So there isn't much we can do to help you besides say make sure you use official Orical JRE for decompiling.
