### ISSUE TITLE
[FG 2.3] setupCiWorkspace Task Failure During applyBinaryPatches

### ISSUE THREAD

**Issue by Leo3418** [MinecraftForge/ForgeGradle#623]
With the most recent build of ForgeGradle 2.3 as of this ticket was written (`2.3-SNAPSHOT-5ce6d6f3`), the `setupCiWorkspace` task fails at the `applyBinaryPatches` step if it is executed in a fresh new environment.
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':applyBinaryPatches'.
> There is a binary discrepency between the expected input class
net.minecraft.client.renderer.entity.layers.LayerHeldItem (ccc) and the actual class.
Checksum on disk is da0f6687, in patch 5f7c661a. Things are probably about to go
very wrong. Did you put something into the jar file?
```

The last ForgeGradle 2.3 build without this problem that I know is `7764e3e`.

## Full Logs
- https://gist.github.com/Leo3418/fb3b1455747cf08ce7f39d8a21446b66
- https://api.travis-ci.org/v3/job/581484827/log.txt (Travis CI build log, at the very end of it)

## Platforms
I have reproduced this issue on the following platforms:
- OpenJDK 1.8.0_222, Gradle wrapper 4.9, Ubuntu 16.04.6
- OpenJDK 1.8.0_222, Gradle wrapper 4.9, Fedora 30
- OpenJDK 1.8.0_222, Gradle wrapper 2.14, Fedora 30
- OpenJDK 1.8.0_222, Gradle wrapper 4.9, Windows 10 1903
- Oracle JDK 1.8.0_171, Gradle wrapper 4.9, Windows 10 1903

All operating systems I used were 64-bit.  
In every attempt, the Minecraft Forge version was `14.23.5.2768`.  
The Gradle cache directory (the `.gradle/` under home directory by default) was deleted before every attempt.

**Comment by Niko-sk2x** [comment]
For me it doesn't happen with latest forge version, but I can reproduce it with forge `1.12.2-14.23.5.2838`. After attempted build on 2838, even latest forge breaks on the same gradle cache. It doesn't happen with `setupDecompWorkspace` (it doesn't appear to use binary patches)

**Comment by bs2609** [comment]
Probably caused by #619, for the same issue as described in #499 and https://github.com/ModCoderPack/MCInjector/pull/4.

(As seen in https://github.com/MinecraftForge/ForgeGradle/pull/499#issuecomment-383395718, same patch/checksums in failure message.)

**Comment by Leo3418** [comment]
@Barteks2x 
> For me it doesn't happen with latest forge version, but I can reproduce it with forge `1.12.2-14.23.5.2838`. After attempted build on 2838, even latest forge breaks on the same gradle cache. It doesn't happen with `setupDecompWorkspace` (it doesn't appear to use binary patches)

Interestingly, `14.23.5.2838` worked without any issue for me as I tried it just now.

I'd better mention that I deleted the Gradle cache directory (`~/.gradle/` by default) before I ran `setupCiWorkspace`, using Forge `14.23.5.2768` (the newest recommended version). However, on 2768 I can run `setupCiWorkspace` after `setupDecompWorkspace` without errors.

**Comment by TBoshoven** [comment]
I can confirm this is broken for me, with both 1.12.2-14.23.5.2807 and 2838 .
Builds run in a clean environment (CircleCI with busted cache).
Locally my builds were fine, but a `cleanCache` triggered this issue.
Deleting the `~/.gradle` directory did not change a thing.

**Comment by BrainStone** [comment]
Can confirm this happening on my CI (that makes clean builds)

**Comment by snowe2010** [comment]
Seeing it with `14.23.4.2764`

**Comment by tterrag1098** [comment]
Should have been fixed via 6084129e4f407eca9fee6826aaa3276fe796553e, try with --refresh-dependencies

**Comment by snowe2010** [comment]
No dice, not to mention that that fix was 2 hours ago and my first time ever using ForgeGradle was in the past 30 minutes 😜 

```
{ ForestryMC } mc-1.12 » ./gradlew clean build --refresh-dependencies                                                                          /cygdrive/c/Users/Tyler/Documents/dev/play/ForestryMC 130
This mapping 'stable_39' was designed for MC 1.12! Use at your own peril.
Archives upload disabled, mavenDir in gradle.properties is missing.
Found AccessTransformer: forestry_at.cfg
:clean UP-TO-DATE
:deobfCompileDummyTask
:getVersionJson
:extractUserdev UP-TO-DATE
:downloadClient SKIPPED
:downloadServer SKIPPED
:splitServerJar SKIPPED
:mergeJars SKIPPED
:applyBinaryPatches FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':applyBinaryPatches'.
> There is a binary discrepency between the expected input class net.minecraft.client.renderer.entity.layers.LayerHeldItem (ccc) and the actual class. Checksum on disk is da0f6687, in patch 5f7c661a. Things are probably about to go very wrong. Did you put something into the jar file?

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 30s
5 actionable tasks: 3 executed, 2 up-to-date
{ ForestryMC } mc-1.12 »                     
 ```

**Comment by LexManos** [comment]
delete your cache and let everything rebuild.
That, or we may need a new Forge build.

**Comment by snowe2010** [comment]
Still happening. 

<details>
<summary>Details</summary>

```
{ ForestryMC } mc-1.12 » rm -rf /cygdrive/c/Users/Tyler/.gradle/caches                                                                         /cygdrive/c/Users/Tyler/Documents/dev/play/ForestryMC 130
{ ForestryMC } mc-1.12 » ./gradlew clean build --refresh-dependencies                                                                              /cygdrive/c/Users/Tyler/Documents/dev/play/ForestryMC
Starting a Gradle Daemon, 1 stopped Daemon could not be reused, use --status for details
Download http://files.minecraftforge.net/maven/net/minecraftforge/gradle/ForgeGradle/2.3-SNAPSHOT/maven-metadata.xml
Download http://files.minecraftforge.net/maven/net/minecraftforge/gradle/ForgeGradle/2.3-SNAPSHOT/ForgeGradle-2.3-20190904.022048-42.pom
Download https://plugins.gradle.org/m2/gradle/plugin/se/bjurr/gitchangelog/git-changelog-gradle-plugin/1.47/git-changelog-gradle-plugin-1.47.pom
Download https://plugins.gradle.org/m2/gradle/plugin/com/matthewprenger/CurseGradle/1.0.9/CurseGradle-1.0.9.pom
Download https://jcenter.bintray.com/com/cloudbees/diff4j/1.1/diff4j-1.1.pom
Download https://jcenter.bintray.com/net/sf/opencsv/opencsv/2.3/opencsv-2.3.pom
Download https://jcenter.bintray.com/com/cloudbees/cloudbees-oss-parent/1/cloudbees-oss-parent-1.pom
Download https://jcenter.bintray.com/com/github/jponge/lzma-java/1.3/lzma-java-1.3.pom
Download https://jcenter.bintray.com/com/nothome/javaxdelta/2.0.1/javaxdelta-2.0.1.pom
Download https://jcenter.bintray.com/com/github/abrarsyed/jastyle/jAstyle/1.3/jAstyle-1.3.pom
Download https://jcenter.bintray.com/org/sonatype/oss/oss-parent/7/oss-parent-7.pom
Download https://jcenter.bintray.com/net/sf/trove4j/trove4j/2.1.0/trove4j-2.1.0.pom
Download https://jcenter.bintray.com/com/google/code/gson/gson/2.2.4/gson-2.2.4.pom
Download https://jcenter.bintray.com/com/github/tony19/named-regexp/0.2.3/named-regexp-0.2.3.pom
Download https://jcenter.bintray.com/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.pom
Download https://jcenter.bintray.com/org/apache/httpcomponents/httpmime/4.3.3/httpmime-4.3.3.pom
Download https://jcenter.bintray.com/org/apache/httpcomponents/httpcomponents-client/4.3.3/httpcomponents-client-4.3.3.pom
Download https://jcenter.bintray.com/org/apache/httpcomponents/project/7/project-7.pom
Download https://jcenter.bintray.com/org/apache/apache/13/apache-13.pom
Download http://files.minecraftforge.net/maven/net/minecraftforge/forgeflower/1.0.342-SNAPSHOT/maven-metadata.xml
Download http://files.minecraftforge.net/maven/net/minecraftforge/forgeflower/1.0.342-SNAPSHOT/forgeflower-1.0.342-20171208.041249-7.pom
Download https://jcenter.bintray.com/se/bjurr/gitchangelog/git-changelog-lib/1.68/git-changelog-lib-1.68.pom
Download https://jcenter.bintray.com/org/jvnet/localizer/localizer/1.12/localizer-1.12.pom
Download https://jcenter.bintray.com/org/jvnet/localizer/localizer-parent/1.12/localizer-parent-1.12.pom
Download https://jcenter.bintray.com/org/apache/apache/4/apache-4.pom
Download https://jcenter.bintray.com/trove/trove/1.0.2/trove-1.0.2.pom
Download https://jcenter.bintray.com/com/squareup/retrofit2/converter-gson/2.0.0/converter-gson-2.0.0.pom
Download https://jcenter.bintray.com/org/gitlab/java-gitlab-api/1.2.7/java-gitlab-api-1.2.7.pom
Download https://jcenter.bintray.com/com/squareup/okhttp/okhttp/2.7.5/okhttp-2.7.5.pom
Download https://jcenter.bintray.com/org/eclipse/jgit/org.eclipse.jgit/3.6.2.201501210735-r/org.eclipse.jgit-3.6.2.201501210735-r.pom
Download https://jcenter.bintray.com/com/jayway/jsonpath/json-path/2.1.0/json-path-2.1.0.pom
Download https://jcenter.bintray.com/com/github/spullara/mustache/java/compiler/0.8.18/compiler-0.8.18.pom
Download https://jcenter.bintray.com/com/squareup/retrofit2/retrofit/2.0.0/retrofit-2.0.0.pom
Download https://jcenter.bintray.com/com/squareup/okhttp/parent/2.7.5/parent-2.7.5.pom
Download https://jcenter.bintray.com/com/squareup/retrofit2/retrofit-converters/2.0.0/retrofit-converters-2.0.0.pom
Download https://jcenter.bintray.com/com/squareup/retrofit2/parent/2.0.0/parent-2.0.0.pom
Download https://jcenter.bintray.com/com/github/spullara/mustache/java/mustache.java/0.8.18/mustache.java-0.8.18.pom
Download https://jcenter.bintray.com/org/eclipse/jgit/org.eclipse.jgit-parent/3.6.2.201501210735-r/org.eclipse.jgit-parent-3.6.2.201501210735-r.pom
Download https://jcenter.bintray.com/org/sonatype/oss/oss-parent/9/oss-parent-9.pom
Download https://jcenter.bintray.com/com/squareup/okio/okio/1.6.0/okio-1.6.0.pom
Download https://jcenter.bintray.com/com/squareup/okio/okio-parent/1.6.0/okio-parent-1.6.0.pom
Download https://jcenter.bintray.com/org/slf4j/slf4j-api/1.7.13/slf4j-api-1.7.13.pom
Download https://jcenter.bintray.com/net/minidev/json-smart/2.2/json-smart-2.2.pom
Download https://jcenter.bintray.com/org/slf4j/slf4j-parent/1.7.13/slf4j-parent-1.7.13.pom
Download https://jcenter.bintray.com/com/squareup/okhttp3/okhttp/3.2.0/okhttp-3.2.0.pom
Download https://jcenter.bintray.com/com/squareup/okhttp3/parent/3.2.0/parent-3.2.0.pom
Download https://jcenter.bintray.com/com/jcraft/jsch/0.1.50/jsch-0.1.50.pom
Download https://jcenter.bintray.com/com/googlecode/javaewah/JavaEWAH/0.7.9/JavaEWAH-0.7.9.pom
Download https://jcenter.bintray.com/org/sonatype/oss/oss-parent/5/oss-parent-5.pom
Download https://jcenter.bintray.com/org/sonatype/oss/oss-parent/6/oss-parent-6.pom
Download https://jcenter.bintray.com/com/fasterxml/oss-parent/19/oss-parent-19.pom
Download https://jcenter.bintray.com/com/fasterxml/oss-parent/18/oss-parent-18.pom
Download https://jcenter.bintray.com/org/ow2/ow2/1.3/ow2-1.3.pom
Download https://jcenter.bintray.com/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.pom
Download https://jcenter.bintray.com/com/google/code/gson/gson/2.6.2/gson-2.6.2.pom
Download https://jcenter.bintray.com/com/google/code/gson/gson-parent/2.6.2/gson-parent-2.6.2.pom
Download https://jcenter.bintray.com/org/apache/apache/9/apache-9.pom
Download https://jcenter.bintray.com/com/cloudbees/diff4j/1.1/diff4j-1.1.jar
Download https://jcenter.bintray.com/net/sf/opencsv/opencsv/2.3/opencsv-2.3.jar
Download http://files.minecraftforge.net/maven/net/minecraftforge/gradle/ForgeGradle/2.3-SNAPSHOT/ForgeGradle-2.3-20190904.022048-42.jar
Download https://plugins.gradle.org/m2/gradle/plugin/se/bjurr/gitchangelog/git-changelog-gradle-plugin/1.47/git-changelog-gradle-plugin-1.47.jar
Download https://plugins.gradle.org/m2/gradle/plugin/com/matthewprenger/CurseGradle/1.0.9/CurseGradle-1.0.9.jar
Download https://jcenter.bintray.com/com/github/spullara/mustache/java/compiler/0.8.18/compiler-0.8.18.jar
Download https://jcenter.bintray.com/com/github/jponge/lzma-java/1.3/lzma-java-1.3.jar
Download https://jcenter.bintray.com/com/nothome/javaxdelta/2.0.1/javaxdelta-2.0.1.jar
Download https://jcenter.bintray.com/com/github/abrarsyed/jastyle/jAstyle/1.3/jAstyle-1.3.jar
Download https://jcenter.bintray.com/com/squareup/retrofit2/converter-gson/2.0.0/converter-gson-2.0.0.jar
Download https://jcenter.bintray.com/se/bjurr/gitchangelog/git-changelog-lib/1.68/git-changelog-lib-1.68.jar
Download https://jcenter.bintray.com/com/github/tony19/named-regexp/0.2.3/named-regexp-0.2.3.jar
Download http://files.minecraftforge.net/maven/net/minecraftforge/forgeflower/1.0.342-SNAPSHOT/forgeflower-1.0.342-20171208.041249-7.jar
Download https://jcenter.bintray.com/org/jvnet/localizer/localizer/1.12/localizer-1.12.jar
Download https://jcenter.bintray.com/org/gitlab/java-gitlab-api/1.2.7/java-gitlab-api-1.2.7.jar
Download https://jcenter.bintray.com/com/jayway/jsonpath/json-path/2.1.0/json-path-2.1.0.jar
Download https://jcenter.bintray.com/trove/trove/1.0.2/trove-1.0.2.jar
Download https://jcenter.bintray.com/com/squareup/okhttp/okhttp/2.7.5/okhttp-2.7.5.jar
Download https://jcenter.bintray.com/com/squareup/retrofit2/retrofit/2.0.0/retrofit-2.0.0.jar
Download https://jcenter.bintray.com/com/squareup/okhttp3/okhttp/3.2.0/okhttp-3.2.0.jar
Download https://jcenter.bintray.com/com/squareup/okio/okio/1.6.0/okio-1.6.0.jar
Download https://jcenter.bintray.com/org/slf4j/slf4j-api/1.7.13/slf4j-api-1.7.13.jar
Download https://jcenter.bintray.com/net/minidev/json-smart/2.2/json-smart-2.2.jar
Download https://jcenter.bintray.com/com/jcraft/jsch/0.1.50/jsch-0.1.50.jar
Download https://jcenter.bintray.com/org/eclipse/jgit/org.eclipse.jgit/3.6.2.201501210735-r/org.eclipse.jgit-3.6.2.201501210735-r.jar
Download https://jcenter.bintray.com/com/google/code/gson/gson/2.6.2/gson-2.6.2.jar
Download https://jcenter.bintray.com/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
Download https://jcenter.bintray.com/com/googlecode/javaewah/JavaEWAH/0.7.9/JavaEWAH-0.7.9.jar
This mapping 'stable_39' was designed for MC 1.12! Use at your own peril.
Archives upload disabled, mavenDir in gradle.properties is missing.
#################################################
         ForgeGradle 2.3-SNAPSHOT-5ce6d6f3
  https://github.com/MinecraftForge/ForgeGradle
#################################################
                 Powered by MCP
             http://modcoderpack.com
     by: Searge, ProfMobius, R4wk, ZeuX
     Fesh0r, IngisKahn, bspkrs, LexManos
#################################################
Found AccessTransformer: forestry_at.cfg
Download http://maven.mcmoddev.com/net/darkhax/tesla/Tesla-1.12/1.0.60/Tesla-1.12-1.0.60.pom
Download http://dvs1.progwml6.com/files/maven/mezz/jei/jei_1.12.2/4.13.1.222/jei_1.12.2-4.13.1.222.pom
Download http://maven.ic2.player.to/net/industrial-craft/industrialcraft-2/2.8.90-ex112/industrialcraft-2-2.8.90-ex112.pom
Download http://maven.modmuss50.me/TechReborn/TechReborn-1.12.2/2.13.2.561/TechReborn-1.12.2-2.13.2.561.pom
Download https://mod-buildcraft.com/maven/com/mod-buildcraft/buildcraft-api/7.99.17/buildcraft-api-7.99.17.pom
Download http://maven.mcmoddev.com/net/darkhax/tesla/Tesla-1.12/1.0.60/Tesla-1.12-1.0.60.jar
Download http://dvs1.progwml6.com/files/maven/mezz/jei/jei_1.12.2/4.13.1.222/jei_1.12.2-4.13.1.222-api.jar
Download http://maven.ic2.player.to/net/industrial-craft/industrialcraft-2/2.8.90-ex112/industrialcraft-2-2.8.90-ex112-api.jar
Download http://maven.modmuss50.me/TechReborn/TechReborn-1.12.2/2.13.2.561/TechReborn-1.12.2-2.13.2.561-api.jar
Download https://mod-buildcraft.com/maven/com/mod-buildcraft/buildcraft-api/7.99.17/buildcraft-api-7.99.17.jar
Download http://maven.mcmoddev.com/net/darkhax/tesla/Tesla-1.12/1.0.60/Tesla-1.12-1.0.60-sources.jar
Download http://dvs1.progwml6.com/files/maven/mezz/jei/jei_1.12.2/4.13.1.222/jei_1.12.2-4.13.1.222-sources.jar
Download http://maven.modmuss50.me/TechReborn/TechReborn-1.12.2/2.13.2.561/TechReborn-1.12.2-2.13.2.561-sources.jar
Download https://mod-buildcraft.com/maven/com/mod-buildcraft/buildcraft-api/7.99.17/buildcraft-api-7.99.17-sources.jar
:clean UP-TO-DATE
:deobfCompileDummyTask
:getVersionJson
:extractUserdev
Download https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.4.2764/forge-1.12.2-14.23.4.2764.pom
Download https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.4.2764/forge-1.12.2-14.23.4.2764-userdev.jar
:downloadClient
:downloadServer
:splitServerJar
:mergeJars
:applyBinaryPatches FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':applyBinaryPatches'.
> There is a binary discrepency between the expected input class net.minecraft.client.renderer.entity.layers.LayerHeldItem (ccc) and the actual class. Checksum on disk is da0f6687, in patch 5f7c661a. Things are probably about to go very wrong. Did you put something into the jar file?

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 1m 18s
9 actionable tasks: 8 executed, 1 up-to-date
```

</details>

**Comment by LexManos** [comment]
Github screwed up.
Verified it works:
```
Z:\tmp>gradlew --console=plain setupCiWorkspace
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/2.14/userguide/gradle_daemon.html.
This mapping 'snapshot_20171003' was designed for MC 1.12! Use at your own peril.
#################################################
         ForgeGradle 2.3-SNAPSHOT-6084129e
  https://github.com/MinecraftForge/ForgeGradle
#################################################
                 Powered by MCP
             http://modcoderpack.com
     by: Searge, ProfMobius, R4wk, ZeuX
     Fesh0r, IngisKahn, bspkrs, LexManos
#################################################
:deobfCompileDummyTask
:getVersionJson
:extractUserdev
Download https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2847/forge-1.12.2-14.23.5.2847.pom
Download https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2847/forge-1.12.2-14.23.5.2847-userdev.jar
:downloadClient SKIPPED
:downloadServer SKIPPED
:splitServerJar SKIPPED
:mergeJars SKIPPED
:applyBinaryPatches
:deobfProvidedDummyTask
:extractDependencyATs SKIPPED
:extractMcpData SKIPPED
:extractMcpMappings SKIPPED
:genSrgs SKIPPED
:deobfMcMCP
Applying SpecialSource...
Applying Exceptor...
:setupCiWorkspace

BUILD SUCCESSFUL

**Comment by TBoshoven** [comment]
I can confirm it now works. Thank you!

**Comment by Leo3418** [comment]
I have tested the latest commit, it was working fine again, thank you developers!

**Comment by fwcd** [comment]
Still having this issue when trying to build [RFTools](https://github.com/McJtyMods/RFTools) using `./gradlew clean build --refresh-dependencies`:

<details><summary><b>Output Log</b></summary>
<p>

```
This mapping 'snapshot_20180504' was designed for MC 1.12! Use at your own peril.
#################################################
         ForgeGradle 2.3-SNAPSHOT-6084129e
  https://github.com/MinecraftForge/ForgeGradle
#################################################
...
Execution failed for task ':applyBinaryPatches'.
> There is a binary discrepency between the expected input class net.minecraft.client.renderer.entity.layers.LayerHeldItem (ccc) and the actual class. Checksum on disk is 5f7c661a, in patch da0f6687. Things are probably about to go very wrong. Did you put something into the jar file?
```

</p>
</details>

Strangely, the checksums here are precisely swapped compared to the error messages in this thread: I am getting

`Checksum on disk is 5f7c661a, in patch da0f6687`

instead of

`Checksum on disk is da0f6687, in patch 5f7c661a`

**Comment by dixiatielu** [comment]
Still having this when I tried to build my mod through GitHub Action.
I tried `./gradlew clean build --refresh-dependencies`,`./gradlew build`,`./gradlew build --no-daemon`. But they still failed in the same step.
My Forge version is `14.23.5.2846`with the mapping-version `snapshot_20171003` for Minecraft 1.12.2.
```
:applyBinaryPatches FAILED

FAILURE: Build failed with an exception.

* What went wrong:

Execution failed for task ':applyBinaryPatches'.
BUILD FAILED
> There is a binary discrepency between the expected input class net.minecraft.client.renderer.entity.layers.LayerHeldItem (ccc) and the actual class. Checksum on disk is 5f7c661a, in patch da0f6687. Things are probably about to go very wrong. Did you put something into the jar file?
```

**Comment by DaemonUmbra** [comment]
FG2.3 is no longer in development, if you want to you can upgrade the 1.12.2 Forge branch to use FG3.

**Comment by dixiatielu** [comment]
> FG2.3 is no longer in development, if you want to you can upgrade the 1.12.2 Forge branch to use FG3.

Thank you, but is there any way to upgrade it? I found an [issue](https://github.com/MinecraftForge/ForgeGradle/issues/607) that says there's no way to upgrade to FG3 if you're developing mods for Minecraft 1.12.2.

**Comment by DaemonUmbra** [comment]
~~I believe that comment was made before the FG3 update that made it possible~~
Evidently I was wrong, more backend work is required to make it work
